stages:
  - build


variables:
  DOCKER_REGISTRY: 192.168.88.90:5000
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""



build_server:
  image: docker:24.0.5
  services:
    - name: docker:24.0.5-dind
      command: ["--tls=false", "--insecure-registry=192.168.88.90:5000"]
  stage: build
  script:

    - cd app           
    - docker build -t $DOCKER_REGISTRY/test-app:latest .  
    - docker push $DOCKER_REGISTRY/test-app:latest       
    - echo "Done"  
  tags:
    - build

                         

